export const LOAD_MAIN_REQUEST = "photo/LOAD_MAIN_REQUEST";
export const LOAD_MAIN_SUCCESS = "photo/LOAD_MAIN_SUCCESS";
export const LOAD_MAIN_ERROR = "photo/LOAD_MAIN_ERROR";

export const LOAD_FEEDS_REQUEST = "photo/LOAD_FEEDS_REQUEST";
export const LOAD_FEEDS_SUCCESS = "photo/LOAD_FEEDS_SUCCESS";
export const LOAD_FEEDS_ERROR = "photo/LOAD_FEEDS_ERROR";

export const LOAD_SHOP_REQUEST = "photo/LOAD_SHOP_REQUEST";
export const LOAD_SHOP_SUCCESS = "photo/LOAD_SHOP_SUCCESS";
export const LOAD_SHOP_ERROR = "photo/LOAD_SHOP_ERROR";

export const UPLOAD_IMG_REQUEST = "photo/UPLOAD_IMG_REQUEST";
export const UPLOAD_IMG_SUCCESS = "photo/UPLOAD_IMG_SUCCESS";
export const UPLOAD_IMG_ERROR = "photo/UPLOAD_IMG_ERROR";

export const ADD_PICSTORY_REQUEST = "photo/ADD_PICSTORY_REQUEST";
export const ADD_PICSTORY_SUCCESS = "photo/ADD_PICSTORY_SUCCESS";
export const ADD_PICSTORY_ERROR = "photo/ADD_PICSTORY_ERROR";

export const LOAD_PICSTORY_REQUEST = "photo/LOAD_PICSTORY_REQUEST";
export const LOAD_PICSTORY_SUCCESS = "photo/LOAD_PICSTORY_SUCCESS";
export const LOAD_PICSTORY_ERROR = "photo/LOAD_PICSTORY_ERROR";
