export const LOAD_MAINS_REQUEST = "photo/LOAD_MAINS_REQUEST";
export const LOAD_MAINS_SUCCESS = "photo/LOAD_MAINS_SUCCESS";
export const LOAD_MAINS_ERROR = "photo/LOAD_MAINS_ERROR";

export const LOAD_FEEDS_REQUEST = "photo/LOAD_FEEDS_REQUEST";
export const LOAD_FEEDS_SUCCESS = "photo/LOAD_FEEDS_SUCCESS";
export const LOAD_FEEDS_ERROR = "photo/LOAD_FEEDS_ERROR";

export const LOAD_SHOPS_REQUEST = "photo/LOAD_SHOPS_REQUEST";
export const LOAD_SHOPS_SUCCESS = "photo/LOAD_SHOPS_SUCCESS";
export const LOAD_SHOPS_ERROR = "photo/LOAD_SHOPS_ERROR";

export const LOAD_DETAIL_REQUEST = "photo/LOAD_DETAIL_REQUEST";
export const LOAD_DETAIL_SUCCESS = "photo/LOAD_DETAIL_SUCCESS";
export const LOAD_DETAIL_ERROR = "photo/LOAD_DETAIL_ERROR";

export const UPLOAD_IMG_REQUEST = "photo/UPLOAD_IMG_REQUEST";
export const UPLOAD_IMG_SUCCESS = "photo/UPLOAD_IMG_SUCCESS";
export const UPLOAD_IMG_ERROR = "photo/UPLOAD_IMG_ERROR";

export const ADD_PICSTORY_REQUEST = "photo/ADD_PICSTORY_REQUEST";
export const ADD_PICSTORY_SUCCESS = "photo/ADD_PICSTORY_SUCCESS";
export const ADD_PICSTORY_ERROR = "photo/ADD_PICSTORY_ERROR";

export const LOAD_PICSTORY_REQUEST = "photo/LOAD_PICSTORY_REQUEST";
export const LOAD_PICSTORY_SUCCESS = "photo/LOAD_PICSTORY_SUCCESS";
export const LOAD_PICSTORY_ERROR = "photo/LOAD_PICSTORY_ERROR";

export const ADD_PHOTO_REQUEST = "photo/ADD_PHOTO_REQUEST";
export const ADD_PHOTO_SUCCESS = "photo/ADD_PHOTO_SUCCESS";
export const ADD_PHOTO_ERROR = "photo/ADD_PHOTO_ERROR";

export const DECLARE_PHOTO_REQUEST = "photo/DECLARE_PHOTO_REQUEST";
export const DECLARE_PHOTO_SUCCESS = "photo/DECLARE_PHOTO_SUCCESS";
export const DECLARE_PHOTO_ERROR = "photo/DECLARE_PHOTO_ERROR";

export const LIKE_PHOTO_REQUEST = "photo/LIKE_PHOTO_REQUEST";
export const LIKE_PHOTO_SUCCESS = "photo/LIKE_PHOTO_SUCCESS";
export const LIKE_PHOTO_ERROR = "photo/LIKE_PHOTO_ERROR";

export const UNLIKE_PHOTO_REQUEST = "photo/UNLIKE_PHOTO_REQUEST";
export const UNLIKE_PHOTO_SUCCESS = "photo/UNLIKE_PHOTO_SUCCESS";
export const UNLIKE_PHOTO_ERROR = "photo/UNLIKE_PHOTO_ERROR";

export const LOAD_SEARCH_REQUEST = "photo/LOAD_SEARCH_REQUEST";
export const LOAD_SEARCH_SUCCESS = "photo/LOAD_SEARCH_SUCCESS";
export const LOAD_SEARCH_ERROR = "photo/LOAD_SEARCH_ERROR";

export const DELETE_LIST = "photo/DELETE_LIST";
